# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'UPTEthereumSigner-Example' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for UPTEthereumSigner-Example
  pod 'UPTEthereumSigner'

  target 'UPTEthereumSigner-ExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
